- name: Copy Elasticsearch repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: present

- name: Start and enable Elasticsearch service
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: true