- name: Set Hostname
  ansible.builtin.shell: set-hostname elasticsearch

- name: Copy Elasticsearch repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: present

- name: Start and enable Elasticsearch service
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: true

- name: Install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: present

- name: Start and enable Elasticsearch service
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: true

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
