- name: Set Hostname
  ansible.builtin.shell: set-hostname elk

- name: Copy Elasticsearch repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ELK
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
        - elasticsearch
        - kibana
        - logstash
        - nginx

- name: Start and enable Elasticsearch service
  ansible.builtin.systemd_service:
    name: "{{item}}"
    state: started
    enabled: true
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
