- name: Copy Elasticsearch repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: present

