format_version: 10
pipelines:
  prometheus:
    group: tools
    label_template: ${COUNT}
    materials:
      ansible:
        git: https://github.com/kn-10/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]
                    working_directory: prometheus

                - exec:
                    command: terraform
                    arguments: [ "apply", "-auto-approve" ]
                    working_directory: prometheus





