format_version: 10
pipelines:
  prometheus-ansible:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/kn-10/miscellaneous-code
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              timeout: 0
              tasks:
                - exec:
                    working_directory: prometheus
                    command: bash
                    arguments: [ "ansible.sh" ]


